---
extends:
- eslint:all
plugins:
- jest
overrides:
- files:
  - __tests__/**/*.spec.js
  env:
    jest: true
- files:
  - src/**/*.js
env:
  es6: true
  node: true
parserOptions:
  sourceType: module
rules:
  quotes:
  - error
  - single
  space-before-function-paren:
  - error
  - never
  padded-blocks:
  - error
  - never
  quote-props:
  - error
  - as-needed
  sort-imports: off
  id-length: off
  sort-keys: off
  camelcase: off
  no-magic-numbers: off
  function-paren-newline: off
  no-extra-parens: off
  default-case: off
  no-plusplus: off
  strict: off
  capitalized-comments: off
  object-property-newline: off
  dot-location: off
  multiline-ternary: off
  max-statements: off
  no-ternary: off
  init-declarations: off
  valid-jsdoc: off
  no-sync: off
  func-style: off
  no-process-env: off
  no-param-reassign: off
  max-lines-per-function: off
  global-require: off
  require-jsdoc: off
  no-prototype-builtins: off
  no-continue: off
  require-unicode-regexp: off
  max-params:
  - error
  - 5
  one-var:
  - error
  - never
  indent:
  - error
  - 4
  - SwitchCase: 1
  comma-dangle:
  - error
  - always-multiline
  max-len:
  - error
  - 140
